version: "3.0"

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.1
    container_name: etcd1
    restart: always
    ports:
      - "2379:2379"
    command:
      - etcd
      - --name=etcd1
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd1:2379
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
    volumes:
      - ./data/etcd1:/etcd-data                            # 挂载的数据卷

  etcd2:
    image: quay.io/coreos/etcd:v3.5.1
    container_name: etcd2
    restart: always
    command:
      - etcd
      - --name=etcd2
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd2:2379
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
    volumes:
      - ./data/etcd2:/etcd-data

  etcd3:
    image: quay.io/coreos/etcd:v3.5.1
    container_name: etcd3
    restart: always
    command:
      - etcd
      - --name=etcd3
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd3:2379
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
    volumes:
      - ./data/etcd3:/etcd-data

