version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.14
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
